#!/usr/bin/env ruby

require 'sinatra'
require 'erb'
require 'mini_magick'

# convert images in public to thumbnails
$root = Dir.pwd
$images = "#{$root}/public/assets/images"
$project_images = "#{$images}/projects"
FileUtils.rm_f("#{$project_images}/thumbnails")
FileUtils::mkdir "#{$project_images}/thumbnails" unless File.directory?("#{$project_images}/thumbnails")

# convert all images to thumbnails when program is run
# would have used a database here, but I messed up

Dir["#{$project_images}/*"].each do |image|
    if File.file?(image)

      # imagemagick, more like imagetragic, amirite? 
      # seriously though please dont break my box i know its tempting
      img = MiniMagick::Image.open(image)
      img.resize("400")
      img.crop("400x300+0+0")
      img.write("#{$project_images}/thumbnails/#{File.basename(image)}")
    end
end 



set :bind, '0.0.0.0'

get '/' do
    erb :index
end

get '/assets/images/:file' do
    send_file("/assets/images/#{params[:file
    ]}", disposition: 'inline')
end

get '/about' do
  erb :about
end

get '/code' do
  erb :code
end

not_found do
  status 404
  erb :oops
end

